# coding=utf8
# the above tag defines encoding for this document and is for Python 2.x compatibility

import re

regex = r"(^(?!0)\d{1}$)|(^[A-Z]{1}-?[A-Z]?$)|(^[A-Z]\W?[A-Z]?\s?\W\s?\d\d?\s?\s?:\s?\d\d?\s?\W)|((?!\d)(?!Rpk)[a-zA-Z]{3,})"

test_str = ("2"
            "4"
            "6"
            "8"
            "Z ( 20 : 1 )"
            "b 0,01 A\n"
            "2x\n"
            "r Ø0,05 CZ B\n"
            "g 0,01\n"
            "R2\n"
            "5°\n"
            ",8\n"
            "R0\n"
            "Ø 4,1\n"
            "B\n"
            "-0,1\n"
            "2x Ø19,2 +- 00,05 CT\n"
            "-0,05\n"
            "Ø15,15 +- 0,05\n"
            "1,65\n"
            "-0,1\n"
            "0\n"
            "n11\n"
            ",5\n"
            "R0,\n"
            "R0\n"
            "C\n"
            "C\n"
            "Rz 1,6\n"
            "Rpk 0,2\n"
            "°\n"
            "45\n"
            "E #F\n"
            "Ø4,5 x7 (++ 0,028) È\n"
            "f 0,01 A\n"
            "0,7\n"
            "b 0,01 A\n"
            "c 0,01\n"
            "r Ø0,05 B\n"
            "0,04\n"
            "F\n"
            "1,5 +- 0,1\n"
            "D\n"
            "0\n"
            "dimensions apply to the finished part\n"
            "2 +- 0,1\n"
            "Material: 1.4021\n"
            "c 0,005\n"
            "9,3 +- 0,1\n"
            "Ra 0,8\n"
            "4,8 `0,05\n"
            "0\n"
            "Raw part No:\n"
            "-\n"
            "Rz 0,25\n"
            "Edge finish:\n"
            "-0,2\n"
            "Rz 16\n"
            "-0,05\n"
            "for machined surface\n"
            "B\n"
            "principales and rules according to:\n"
            "1   Start drawing\n"
            "-\n"
            "of form, orientation, location and run-out:\n"
            "DESCRIPTION\n"
            "DRAWN BY INSP. DATE\n"
            "Edge finish according to:\n"
            "REVISION HISTORY\n"
            "Copyright\n"
            "    16%\n"
            "not applicable\n"
            "this document as well as the\n"
            "without\n"
            "    Nominal\n"
            "file:\n"
            "be held liable for the payment\n"
            "the event\n"
            "A\n"
            "A\n"
            "of the grant of a patent,\n"
            "Scale:\n"
            "Projection:\n"
            "Valid for all untoleranced dimensions:\n"
            "d 0,2 A B\n"
            "-\n"
            "2:1\n"
            "mm\n"
            "Description:\n"
            "F   Cleanliness:\n"
            "11.07.2018\n"
            "F\n"
            "    Part\n"
            "of deposits, detachable\n"
            "Design Freeze Release B1 -Sample"
            "Page:\n"
            "    Delivery\n"
            "tbd\n"
            "ENGINE Division"
            "5129275\n"
            "1/1\n"
            "2\n"
            "4\n"
            "6\n"
            "A3\n")

matches = re.sub(regex,"" ,test_str)

print(test_str)